---
title: "R Notebook"
output: html_notebook
---

Generates figures of EK60 Data

Load in libraries

```{r}
library(tidyverse)
library(lubridate)
```


## EK60

Read in the data,
I processed these data elsewhere, so as to avoid overloading this directory with intermediate files.
```{r}
dataBinned <- read_csv("data/backscatter_table_go7.csv")
```


Convet to correct time zone
```{r}
dataBinned_01 <- dataBinned %>%
  mutate(timeMex = with_tz(time_bin, tzone = "US/Central") )
```

Some upfront calculations
```{r}
startDay <- dataBinned_01$timeMex %>% na.omit %>% min %>% floor_date(unit = "days")
endDay <- dataBinned_01$timeMex %>% na.omit %>% max %>% ceiling_date(unit = "days")
timeBreaks <- seq(from = startDay, to = endDay, by = "12 hours")
timeLabels <- format(timeBreaks)
```

Plot the 18kHz data (largish animals)
```{r}

# Position of letters
plotLetters <- tribble(
  ~letter, ~depth_bin, ~timeMex,
  "A", 350, as.POSIXct("2017-01-07 13:00:00"),
  "B", 200, as.POSIXct("2017-01-09 23:00:00"),
  "C", 150, as.POSIXct("2017-01-08 13:00:00"),
  "D", 625, as.POSIXct("2017-01-12 07:00:00"),
  "E", 750, as.POSIXct("2017-01-10 02:00:00")
  
)

library(shadowtext)
plot18k <- dataBinned_01 %>% filter(frequency == 18000) %>% ggplot(aes(x = timeMex, y = depth_bin, fill = value)) + geom_tile() + scale_y_reverse() + scale_fill_viridis_c(limits = c(-165, -75), oob = scales::squish) +
  scale_x_datetime(breaks = timeBreaks, date_labels = "%d::%H") + labs(x = "day::hour", y = "depth (m)", fill = "backscatter (dB)") + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + geom_hline(yintercept = 160, color = "darkgreen") +
  geom_hline(yintercept = 850, color = "darkblue") +
  geom_shadowtext(data = plotLetters, aes(x = timeMex - 12 * 60^2, y = depth_bin, label = letter),  inherit.aes = FALSE, size = 6, bg.color = "white", color = "black") +
  geom_segment(data = plotLetters, inherit.aes = FALSE, aes(x = timeMex - 9 * 60^2, xend = timeMex, y = depth_bin, yend = depth_bin), arrow = arrow(length = unit(0.03, "npc")), color = "white", size = 1.5) + 
  geom_segment(data = plotLetters, inherit.aes = FALSE, aes(x = timeMex - 9 * 60^2, xend = timeMex, y = depth_bin, yend = depth_bin), arrow = arrow(length = unit(0.03, "npc")))
plot18k

#ggsave("figures/stationP2_EK60_18kOnly.png")
```

Plot all of the other sizes of things

```{r fig.height=20, fig.width = 8}
dataBinned_01 %>% ggplot(aes(x = timeMex, y = depth_bin, fill = value)) + geom_tile() + scale_y_reverse() + scale_fill_viridis_c(limits = c(-165, -75), oob = scales::squish) +
  scale_x_datetime(breaks = timeBreaks, date_labels = "%d::%H") + labs(x = "day::hour", y = "Depth (m)", fill = "backscatter (dB)") + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  
  
  facet_wrap(~frequency, ncol = 1)

#ggsave("figures/stationP2_EK60_go7.svg", width = 4, height = 10)
ggsave("figures/stationP2_EK60_go7.png", width = 6, height = 10)
```