---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(cowplot)
theme_set(theme_cowplot())
```


# Particles Only

# Read In Data

```{r}
bes<- read_csv("dataOut/binned_EachSize.csv")
bds <- read_csv("dataOut/binned_DepthSummary.csv")
ues <- read_csv("dataOut/unbinned_EachSize.csv")
uds <- read_csv("dataOut/unbinned_DepthSummary.csv")
```


# Summary Statistics
```{r}
PlotNParticles <- uds %>% 
  ggplot(aes(x = tot_nparticles, y = depth, col = profile)) +
 facet_wrap(~project) +
 geom_point(alpha = 0.3, shape = 1) +
scale_y_reverse() + scale_x_log10()

PlotNParticles
```

```{r}
PlotPSD <- uds %>% 
  filter(project == "ETNP") %>%
  ggplot(aes(x = psd, y = depth, col = profile)) +
 geom_point(alpha = 0.3, shape = 1) +
  geom_path(aes(x = psd_gam)) + 
scale_y_reverse(limits = c(2500, 0))

PlotPSD
```

Heck. This is wrong...

```{r}
PlotPSD <- uds %>% 
  filter(profile %in% c("stn_043", "p16n_100")) %>%
  ggplot(aes(x = psd, y = depth, col = project)) +
 geom_point(alpha = 0.7, shape = 1) +
  geom_path(aes(x = psd_gam)) +
scale_y_reverse(limits = c(2500, 0)) 

PlotPSD
```