---
title: "R Notebook"
output: html_notebook
---

Link from Andrew McDonnell
https://cchdo.ucsd.edu/cruise/33RO20150410

```{r}
library(tidyverse)
library(oce)
```

```{r}
p16ctd <- read.ctd("data/p16ctd/33RO20150410_00100_00001_ct1.csv")
```

```{r}
p16ctdData <- as.data.frame(p16ctd@data)
```

```{r}
p16ctdData <- p16ctdData %>%
  mutate(sigmaT = swSigmaT(salinity = .$salinity, temperature = .$temperature, pressure = .$pressure)) %>% 
  mutate(CTDBEAMCP = if_else(CTDBEAMCP == -999, NaN, CTDBEAMCP))
```


```{r fig.width = 4, fig.height = 5}
GlobalAdjust = -.5
#plot.new()
plotTempSalOxyP16 <- function(){
  par(mar = c(7,4,4,1))
  plot(p16ctdData$oxygen, p16ctdData$pressure, type = "l", ylim = c(1200, 0), col = "slateblue1", lwd = 8, ylab = "", xlab = "", xaxt = "n", yaxt = "n")
  axis(side = 3, padj = 1, tcl = .5)
  mtext( "Oxygen (µM)", side = 3, line = 1.25)
  #axis(side = 2, padj = 1, tcl = 0.5, at = seq(from = 0, to = 1200, by = 200))
  axis(side = 2, padj = .5, tcl = 0.5, las = 2, mgp = c(0, .3, 0))
   mtext("Depth (m)", side = 2, line = 2, cex = 1.25)
  abline(h = 850, col = "darkblue") 
  abline(h = 170, col = "darkgreen")
  #text(y = 1050, x = 175, labels = "Bottom of OMZ\n (850 m)")
  par(new = TRUE)
  plot(p16ctdData$temperature, p16ctdData$pressure, type = "l", ylim = c(1200, 0), xlim = c(0, 30), col = "firebrick4", lwd = 2, ylab = "", xlab = "", axes = FALSE)
  axis(side = 1, line = 0, padj = GlobalAdjust, tcl = .5)
  mtext( "Temperature (°C)", side = 1, line = 2 + GlobalAdjust)
  par(new = TRUE)
  plot(p16ctdData$salinity, p16ctdData$pressure, type = "l", ylim = c(1200, 0), col = "gray20", lty = "dashed", lwd = 3, axes = FALSE, xlab = "", ylab = "")
  axis(side = 1, line = 3.5, padj = -1, tcl = .5)
  mtext("Salinity (ppt)", side = 1, line = 5 + GlobalAdjust/2)
  legend(x = 34.8, y = 800, legend = c("Oxygen", "Temp", "Sal"), lty = c("solid", "solid", "dashed"), col = c("slateblue1", "firebrick4", "gray20"), lwd = c(8, 2, 3))
  mtext(expression(bold("B")), side = 3, line = 1.3, adj = 0, cex = 2)
}
plotTempSalOxyP16()
```



## Beam SigTheta

```{r fig.width = 4, fig.height = 5}
plotBeamSTP16 <- function(){
  par(mar = c(7,4,4,1))
  
  plot(p16ctdData$sigmaT, p16ctdData$pressure, type = "l", ylim = c(1200, 0), col = "gray40", lty = "dotted", lwd = 5, axes = FALSE, xlab = "", ylab = "")
  #axis(side = 1, line = 2, at = 21:26)
  axis(side = 2, padj = .5, tcl = 0.5, las = 2, mgp = c(0, .3, 0))
   mtext("Depth (m)", side = 2, line = 2, cex = 1.25)
  axis(side = 3, line = 0,  padj = 1, tcl = .5)
  #mtext(expression(Density~σθ~(kg/m^3)), side = 1, line = 2.2, adj = 1)
  mtext(expression(Density~σθ~(kg/m^3)), side = 3, line = 1)
  
  
  par(new = TRUE)
  plot(p16ctdData$CTDBEAMCP, p16ctdData$pressure, type = "l", ylim = c(1200, 0), col = "black", lwd = 3, ylab = "", xlab = "", xaxt = "n", yaxt = "n")
  #axis(side = 1, at = seq(from = 0.075, to = 0.175, by = 0.025))
  axis(side = 1,  padj = -1, tcl = .5)
  #mtext( "Beam Attenuation (/m)", side = 1, line = .1, adj = 1)
  mtext( "Beam Attenuation (/m)", side = 1, line = 2 + GlobalAdjust)
  abline(h = 200, col = "darkgreen")
  legend(x = .11, y = 900, legend = c("Beam", "σθ"), lty = c("solid", "dashed"), col = c( "black", "gray40"), lwd = c(8, 3, 5))
  mtext(expression(bold("D")), side = 3, line = 1.3, adj = 0, cex = 2)
}
plotBeamSTP16()

```


# Chlorophyl

Theres no ctd chlorophyl from the P16 cruise. Apparently, physical oceangraphers don't really care?




```{r}
wodChl <- read_csv("data/WODatabaseP16/ocldb1609210461.10411.OSD.csv", skip = 18, n_max = 25, col_names = FALSE) %>% select(Depth = X2, Flu = X5)
```

```{r}
wodChl %>% ggplot(aes(y = Depth, x = Flu)) + geom_point() + scale_y_reverse()
```

Oxyen, Fluo
xlim = c(0, max(wodChl$Flu) * 1.2),
```{r fig.width = 4, fig.height = 5}

plotFluOxyP16 <- function(){
  par(mar = c(4,3,4,0), cex.axis = 1.3)

  plot(p16ctdData$oxygen, p16ctdData$pressure, type = "l", xlim = c(0, 210), ylim = c(200, 0), col = "slateblue1", lwd = 8, ylab = "", xlab = "", axes = FALSE)
  #axis(side = 2, padj = 1, tcl = 0.5, at = c(0, 50, 100, 150, 200))
  axis(side = 2, padj = .5, tcl = 0.5, las = 2, mgp = c(0, .3, 0), at = c(0, 50, 100, 150, 200))
   mtext("Depth (m)", side = 2, line = 2, cex = 1.25)
  axis(side = 3, padj = 1, tcl = .5, at = c(0, 50, 100, 150, 200))
  mtext("Oxygen (µM)", side = 3, line = 1.5)
  
  par(new = TRUE)
  plot(wodChl$Flu, wodChl$Depth, type = "l", ylim = c(200, 0),  col = "darkgreen", lty = "solid", lwd = 3, axes = FALSE, xlab = "", ylab = "")
  axis(side = 1, line = 0, padj = GlobalAdjust, tcl = .5)
  mtext("Fluorescence (RFU)", side = 1, line = 1.5)
  #abline(h = 200, col = "darkgreen")
  #text(labels = "Base of\nPhotic Zone\n(160 m)", x = 1.9, y = 215)
  
  legend(x = .6, y = 130, legend = c("Oxygen", "Fluo"), lty = c("solid", "solid"), col = c("slateblue1", "darkgreen"), lwd = c(8, 3))
  mtext(expression(bold("C")), side = 3, line = 1.3, adj = 0, cex = 2)
}
plotFluOxyP16()
```

# Map

```{r}
library(oceanmap)
library(ncdf4)
library(raster)
library(viridis)
```

https://ro-allen.github.io/oceanmap.html

```{r}
# path to downloaded MODIS-Aqua data
chl.win <- ('data/A20021852020182.L3m_CU_CHL_chlor_a_9km.nc')

# read in MODIS-Aqua data
chl.dat <- nc_open(chl.win)

# convert .nc data to raster data for plotting
chl.dat.raster <- nc2raster(chl.dat, "chlor_a", lonname="lon", latname="lat", date=T)
nc_close(chl.dat)
```

```{r}
chl.flip <- flip(chl.dat.raster, "y")
chl.360 <- shift(raster::rotate(shift(chl.flip, 180)), 180)
```

```{r}
chl.360.crop = raster::crop(chl.flip, extent(c(-160, -130, 10,25 ))) 
```

```{r}
# this does nothing, as in the tutorial
vpal <- viridis(100, alpha = 1, begin = 0, end = 0.4, option = "magma")
```

```{r}
mapP16 <- function(){
v(chl.360.crop, cbpos = "r", pal = "jet", zlim = c(0,.4), cb.xlab = expression("Chlorophyll-a (mg m"^-3*")"), bwd = 0.01, grid = F, replace.na = F, width = 10, height = 5)
points(-152.0002,16.4998, pch = 21, bg = "red", cex = 2)
}
mapP16()

png("figures/P16map.png")
mapP16()
dev.off()
```
```{r}
chl.360.crop = raster::crop(chl.flip, extent(c(-160, -100, 10,30 ))) 
v(chl.360.crop, cbpos = "r", pal = "jet", zlim = c(0,.4), cb.xlab = expression("Chlorophyll-a (mg m"^-3*")"), width = 20)
```

```{r}

```


# All
```{r}
library(imager)
```

```{r}
getwd()
```


```{r}
P16map <- load.image("figures/P16MapManualExport.png")
plotMapP16 <- function(){
  par(mar = c(0,2,2,0))
  plot(P16map, axes = FALSE)
  mtext(expression(bold("A")), side = 3, line = 0, adj = 0, cex = 2)
}
plotMapP16()
```


```{r, fig.width = 10, fig.height = 8}
StationInfoPlot <- function(){
layout(matrix(c(1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
                1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
                3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 
                3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 
                3, 3, 3, 3, 3, 4, 4, 4, 4, 4
)
,5, 10, byrow = TRUE))
plotMapP16()
plotFluOxyP16()
plotTempSalOxyP16()
plotBeamSTP16()
}
StationInfoPlot()
```

```{r}
png(filename = "./figures/CombinedP16S100Info.png", width = 10, height = 8, units = "in", res = 200)
StationInfoPlot()
dev.off()
```
