---
title: "R Notebook"
output: html_notebook
---
Data from Natalia evans

```{r}
library(tidyverse)
library(readxl)
```

```{r}
cb10 <- c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a')
```


```{r}
watermass00 <- read_excel("data/StP2_2017_out.xlsx")
```

```{r}
wmNames <- watermass00 %>% select(TSW:UCDW) %>% colnames
```


```{r}
watermass01 <- watermass00 %>% 
  filter(consv_T < 27) %>%
  select(press:UCDW) %>% 
  pivot_longer(cols = -press, names_to = "watermass") %>%
  mutate(watermass = factor(watermass, levels = wmNames, ordered = TRUE))
```

```{r}
wmCols <- c("gray80", "darkorange", "darkgreen", "yellow", "white", "darkblue", "black")
watermass01 %>% 
  arrange(press) %>%
  #filter(watermass != "UCDW") %>%
  filter(value > 0) %>%
  mutate(value = if_else(value > 1, 1, value)) %>%
  ggplot(aes(x = value, y = press, fill = watermass, shape = watermass, group = watermass)) +
  geom_point(size = 3) +
  #geom_path(color = "black") +
  scale_y_reverse(limits = c(1250, 5)) +
  #scale_y_reverse() +
  scale_x_continuous(limits = c(0, 1)) +
  scale_fill_manual(values = wmCols) + scale_shape_manual(values = c(21:25, 21:25)) +
  cowplot::theme_cowplot()
```

```{r}
ggsave("figures/watermass.png", width = 5, height = 3, dpi = 100)
```

```{r}
wmCols <- c("gray80", "darkorange", "darkgreen", "yellow", "white", "darkblue", "black")
watermass01 %>% 
  arrange(press) %>%
  #filter(watermass != "UCDW") %>%
  filter(value > 0) %>%
  #mutate(value = if_else(value > 1, 1, value)) %>%
  ggplot(aes(x = value, y = press, fill = watermass, shape = watermass, group = watermass)) +
  geom_point(size = 3) +
  #geom_path(color = "black") +
  #scale_y_reverse(limits = c(1250, 5)) +
  scale_y_reverse() +
  scale_x_continuous(limits = c(0, 2)) +
  scale_fill_manual(values = wmCols) + scale_shape_manual(values = c(21:25, 21:25)) +
  cowplot::theme_cowplot()
```

```{r}
ggsave("figures/watermass2.png", width = 5, height = 3, dpi = 100)
```


