---
title: "Manuscript Outline"
author: "Cram"
output: html_document
bibliography: ["../references.bib"]
---

# Abstract




# Figures

Figure 1. Map of the ETNP Oxygen Minimum Zone and the location of station P2. Colors indicate chlorophyll concentrations at the surface, while the red ouline signifies the region containing low oxyegen.

Figure 2. Oceanographic parameters at ETNP station P2 **(A)** temperature **(B)** Salinity, **(C)** Chlophyll Concentrations **(D)** Oxygen concentrations **(E)** Turbidity

Figure 3. A profile of data generated by the UVP. At each depth the abundance of particles at each size are color coded on a log scale. Particle sizes where no particles in that sample were seen are represented with a smaller black dot.

Figure 4. Summary statistics of particle distributions. (A) Total particle numbers, (B) Particle size distribution. Color indicates the time point at which the sample were collected. As we did not detect appreciable differences between the stations, we report the color map for which points connect to which stations in the supplement.

Figure 5. Particle flux, measured from sinking traps large symbols. Data from the "plus particles" and "top collector" samples from both cone and net traps were collated to generate these data. Trap types are shown by the shape and color of the large points. Superimposed are binned estemates of particle flux generated by fitting the particle size distribution to the trap counts.

Figure 6. Binned particle number, slope, and flux for large ($>= 0.53\, \mu m$) and small ($< 0.53 \, \mu m$) particles.

Figure 7. **A** Flux profile from smoothed particle size distributions. Regions where flux is *increasing* are coded as {color}. **B** Particle disaggregation, measured as the descrepancy between the observed and model predicted flux of small particles, devided by the attenuation of large particles. 
Or
The fraction of the decrease in large particle flux that appears as small particle flux.

Figure S1. Observed particle size distribution superimposed and the gam fitted particle mean and bootstrapped 95% prediction intervals of those size distributions. That statisticaclly siginificantly more points fall outside of the prediction intervals than by chance alone suggests that there is more variability between points than predicted by random sampling effects alone.

# References


