---
title: "R Notebook"
output: html_notebook
---

Old EK60 figures that I'm not using now but did use for some research proposals.
You need to first run Generate KK60Figures.Rmd, or this doesn't run.


The krill size fraction
```{r}
plotLetters <- tribble(
  ~letter, ~depth_bin, ~timeMex,
  "A", 300, as.POSIXct("2017-01-07 13:00:00"),
  "B", 200, as.POSIXct("2017-01-09 23:00:00"),
  "C", 150, as.POSIXct("2017-01-08 13:00:00"),
  "D", 625, as.POSIXct("2017-01-12 07:00:00"),
  "E", 750, as.POSIXct("2017-01-10 02:00:00")
  
)

library(shadowtext)
plot38k <- dataBinned_01 %>% filter(frequency == 38000) %>% ggplot(aes(x = timeMex, y = depth_bin, fill = value)) + geom_tile() + scale_y_reverse() + scale_fill_viridis_c(limits = c(-165, -95), oob = scales::squish) +
  scale_x_datetime(breaks = timeBreaks, date_labels = "%d::%H") + labs(x = "Day::Hour", y = "Depth (m)", fill = "Backscatter (dB)") + theme_bw()  + geom_hline(yintercept = 160, color = "darkgreen") +
  geom_hline(yintercept = 850, color = "darkblue") +
  geom_shadowtext(data = plotLetters[1:2,], aes(x = timeMex - 12 * 60^2, y = depth_bin, label = letter),  inherit.aes = FALSE, size = 6, bg.color = "white", color = "black") +
  geom_segment(data = plotLetters[1:2,], inherit.aes = FALSE, aes(x = timeMex - 9 * 60^2, xend = timeMex, y = depth_bin, yend = depth_bin), arrow = arrow(length = unit(0.03, "npc")), color = "white", size = 1.5) + 
  geom_segment(data = plotLetters[1:2,], inherit.aes = FALSE, aes(x = timeMex - 9 * 60^2, xend = timeMex, y = depth_bin, yend = depth_bin), arrow = arrow(length = unit(0.03, "npc"))) +
  theme(axis.text.x = element_text(size = 12,angle = 90, vjust = 0.5),
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 14)
        )
plot38k

ggsave("figures/stationP2_EK60_38kOnly.png")
```


```{r}
plot18k + scale_y_reverse(limits = c(500, 200))
```

Zooplankton size fraction
```{r}
plot200k <- dataBinned_01 %>% filter(frequency == 200000) %>% ggplot(aes(x = timeMex, y = depth_bin, fill = value)) + geom_tile() + scale_y_reverse() + scale_fill_viridis_c(limits = c(-165, -155), oob = scales::squish) +
  scale_x_datetime(breaks = timeBreaks, date_labels = "%d::%H") + labs(x = "day::hour", y = "depth (m)", fill = "backscatter (dB)") + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + geom_hline(yintercept = 160, color = "darkgreen") +
  geom_hline(yintercept = 850, color = "darkblue")
plot200k
```