---
title: "Exploring processed UVP-2017 data"
author: "Jacob Cram"
date: "4/20/2020"
output: html_notebook
---

There are binned and unbinned data that I would like to look at.

First the unbinned data. I want for each, number, biovol, flux, psd,
psd with confidence intervals.
read_csv("dataOut/")

```{r}
library(tidyverse)
library(cowplot)
library(plotly)
```


# Load all data
```{r}
unbinned_DepthSummary <- read_csv("dataOut/unbinned_DepthSummary.csv")
unbinned_EachSize <- read_csv("dataOut/unbinned_EachSize.csv")
binned_DepthSummary <- read_csv("dataOut/binned_DepthSummary.csv")
binned_EachSize <- read_csv("dataOut/binned_EachSize.csv")
```

# Summary

## Binned
```{r}
plot_nparticles <- unbinned_DepthSummary %>% ggplot(aes(x = tot_nparticles, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1) + scale_y_reverse() + scale_x_log10() + guides(colour = FALSE) + labs(x = "#Particles/L") + theme_cowplot()

plot_biovolume <- unbinned_DepthSummary %>% ggplot(aes(x = tot_biovolume, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1) + scale_y_reverse() + scale_x_log10() + guides(colour = FALSE) + labs(x = "Unadjusted Biovolume (mass units/L)")+ theme_cowplot()

plot_flux <- unbinned_DepthSummary %>% ggplot(aes(x = tot_flux, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1) + scale_y_reverse() + scale_x_log10() + guides(colour = FALSE) + labs(x = "Unadjusted Flux (units/m^2/day)")+
   theme_cowplot()

plot_psd <- unbinned_DepthSummary %>% ggplot(aes(x = psd, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1, shape = 21, fill = "black", stroke = 1) + scale_y_reverse()  + guides(colour = FALSE) + labs(x = "Particle Size Distribution Slope") + theme_cowplot()

plot_speed <- unbinned_DepthSummary %>% ggplot(aes(x = tot_speed, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1) + scale_y_reverse() + scale_x_log10() + guides(colour = FALSE) + labs(x = "Unadjusted Flux Weighted Sinking Speed (m/d)") + theme_cowplot()


ggplotly(plot_nparticles)
ggplotly(plot_biovolume)
ggplotly(plot_flux)
ggplotly(plot_speed)
ggplotly(plot_psd)

cowplot::plot_grid(plot_nparticles,plot_biovolume, plot_flux, plot_speed, plot_psd) #%>% ggplotly()
```

```{r}
plot_nparticles
plot_psd + scale_x_continuous(limits = c(-4.6, -2.5))
```

## Binned
```{r}
plot_nparticles <- binned_DepthSummary %>% ggplot(aes(x = tot_nparticles, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1) + scale_y_reverse(breaks = seq(from = 0, to = 2500, by = 100)) + scale_x_log10() + guides(colour = FALSE) + labs(x = "#Particles/L") + theme_cowplot()

plot_biovolume <- binned_DepthSummary %>% ggplot(aes(x = tot_biovolume, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1) + scale_y_reverse() + scale_x_log10() + guides(colour = FALSE) + labs(x = "Unadjusted Biovolume (mass units/L)")+ theme_cowplot()

plot_flux <- binned_DepthSummary %>% ggplot(aes(x = tot_flux, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1) + scale_y_reverse() + scale_x_log10() + guides(colour = FALSE) + labs(x = "Unadjusted Flux (units/m^2/day)")+
   theme_cowplot()

plot_psd <- binned_DepthSummary %>% ggplot(aes(x = psd, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1, shape = 21, fill = "black") + scale_y_reverse()  + guides(colour = FALSE) + labs(x = "Particle Size Distribution Slope") + theme_cowplot()

plot_speed <- binned_DepthSummary %>% ggplot(aes(x = tot_speed, y = depth, colour = profile)) + geom_point(alpha = 0.5, size = 1) + scale_y_reverse() + scale_x_log10() + guides(colour = FALSE) + labs(x = "Unadjusted Flux Weighted Sinking Speed (m/d)") + theme_cowplot()


ggplotly(plot_nparticles)
ggplotly(plot_biovolume)
ggplotly(plot_flux)
ggplotly(plot_speed)
ggplotly(plot_psd)

cowplot::plot_grid(plot_nparticles,plot_biovolume, plot_flux, plot_speed, plot_psd) #%>% ggplotly()

```

